### ISSUE TITLE
Create a wrapper structure for different neurons and create a library for these

### ISSUE THREAD

**Issue by DiGyt** [DiGyt/neuropynamics#8]
A simple library of differential equation based on different neuron models, as used in brian2 is provided here: 

[https://brian2.readthedocs.io/en/stable/introduction/brian1_to_2/library.html?highlight=izhikevich#neuron-models](https://brian2.readthedocs.io/en/stable/introduction/brian1_to_2/library.html?highlight=izhikevich#neuron-models)

**Comment by lucasfldmn** [comment]
Neuron models to do:

- [x] Perfect integrator

- [x] Leaky integrate-and-fire neuron

- [x] FitzHugh-Nagumo-Modell
